import { FirmwareManifestRepository } from ".";
import { UserInvitationRepository } from ".";
import { ApiKeyRepository } from ".";
import { CampaignDeviceMetadataRepository } from ".";
import { CampaignStatisticsRepository } from ".";
import { CampaignStatisticsEventsRepository } from ".";
import { CertificateEnrollmentRepository } from ".";
import { CertificateIssuerRepository } from ".";
import { CertificateIssuerConfigRepository } from ".";
import { DarkThemeColorRepository } from ".";
import { DarkThemeImageRepository } from ".";
import { DeveloperCertificateRepository } from ".";
import { DeviceRepository } from ".";
import { DeviceEnrollmentRepository } from ".";
import { DeviceEnrollmentBulkCreateRepository } from ".";
import { DeviceEnrollmentBulkDeleteRepository } from ".";
import { DeviceEnrollmentDenialRepository } from ".";
import { DeviceEventsRepository } from ".";
import { DeviceGroupRepository } from ".";
import { FirmwareImageRepository } from ".";
import { AccountRepository } from ".";
import { IdentityProviderRepository } from ".";
import { LightThemeColorRepository } from ".";
import { LightThemeImageRepository } from ".";
import { PolicyGroupRepository } from ".";
import { PreSharedKeyRepository } from ".";
import { ServerCredentialsRepository } from ".";
import { SubtenantApiKeyRepository } from ".";
import { SubtenantDarkThemeColorRepository } from ".";
import { SubtenantDarkThemeImageRepository } from ".";
import { SubtenantIdentityProviderRepository } from ".";
import { SubtenantLightThemeColorRepository } from ".";
import { SubtenantLightThemeImageRepository } from ".";
import { SubtenantPolicyGroupRepository } from ".";
import { SubtenantTrustedCertificateRepository } from ".";
import { SubtenantUserRepository } from ".";
import { SubtenantUserInvitationRepository } from ".";
import { TrustedCertificateRepository } from ".";
import { UpdateCampaignRepository } from ".";
import { UserRepository } from ".";
import { Config } from "../common/config";
export declare class Factory {
    private readonly _config;
    constructor(config: Config);
    accountRepository(): AccountRepository;
    apiKeyRepository(): ApiKeyRepository;
    campaignDeviceMetadataRepository(): CampaignDeviceMetadataRepository;
    campaignStatisticsRepository(): CampaignStatisticsRepository;
    campaignStatisticsEventsRepository(): CampaignStatisticsEventsRepository;
    certificateEnrollmentRepository(): CertificateEnrollmentRepository;
    certificateIssuerRepository(): CertificateIssuerRepository;
    certificateIssuerConfigRepository(): CertificateIssuerConfigRepository;
    darkThemeColorRepository(): DarkThemeColorRepository;
    darkThemeImageRepository(): DarkThemeImageRepository;
    developerCertificateRepository(): DeveloperCertificateRepository;
    deviceRepository(): DeviceRepository;
    deviceEnrollmentRepository(): DeviceEnrollmentRepository;
    deviceEnrollmentBulkCreateRepository(): DeviceEnrollmentBulkCreateRepository;
    deviceEnrollmentBulkDeleteRepository(): DeviceEnrollmentBulkDeleteRepository;
    deviceEnrollmentDenialRepository(): DeviceEnrollmentDenialRepository;
    deviceEventsRepository(): DeviceEventsRepository;
    deviceGroupRepository(): DeviceGroupRepository;
    firmwareImageRepository(): FirmwareImageRepository;
    firmwareManifestRepository(): FirmwareManifestRepository;
    identityProviderRepository(): IdentityProviderRepository;
    lightThemeColorRepository(): LightThemeColorRepository;
    lightThemeImageRepository(): LightThemeImageRepository;
    policyGroupRepository(): PolicyGroupRepository;
    preSharedKeyRepository(): PreSharedKeyRepository;
    serverCredentialsRepository(): ServerCredentialsRepository;
    subtenantApiKeyRepository(): SubtenantApiKeyRepository;
    subtenantDarkThemeColorRepository(): SubtenantDarkThemeColorRepository;
    subtenantDarkThemeImageRepository(): SubtenantDarkThemeImageRepository;
    subtenantIdentityProviderRepository(): SubtenantIdentityProviderRepository;
    subtenantLightThemeColorRepository(): SubtenantLightThemeColorRepository;
    subtenantLightThemeImageRepository(): SubtenantLightThemeImageRepository;
    subtenantPolicyGroupRepository(): SubtenantPolicyGroupRepository;
    subtenantTrustedCertificateRepository(): SubtenantTrustedCertificateRepository;
    subtenantUserRepository(): SubtenantUserRepository;
    subtenantUserInvitationRepository(): SubtenantUserInvitationRepository;
    trustedCertificateRepository(): TrustedCertificateRepository;
    updateCampaignRepository(): UpdateCampaignRepository;
    userRepository(): UserRepository;
    userInvitationRepository(): UserInvitationRepository;
}
